server {
    listen 80 default_server;

    root   /usr/share/nginx/html; 
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/frontend.access.log;
    error_log /var/log/nginx/frontend.error.log;
}
