# ./nginx.conf (za uporabo v Dockerfile frontend-a)
server {
    listen 8080; # Nginx v kontejnerju posluša na tem portu
    server_name localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
