export const infrastructureStatus = [
    "active",
    "idle",
    "broken",
    "inrepair",
    "outofservice",
    "cleaning",
    "undefined"
];
export const mineStatuses = [
    "active",
    "idle",
    "closed",
    "building"
];
export const mineTypes = [
    "surface",
    "underground",
    "placer",
    "insitu",
    "deepsea"
];
export const mineralGrades = [
    "low",
    "medium",
    "high",
    "undefined"
];
export const workerTypes = [
    "miner",
    "machineoperator",
    "blastingtechnician",
    "maintenanceworker",
    "surveyor",
    "geologist",
    "miningengineer",
    "safetytechnician",
    "ventilationengineer",
    "hydrologist",
    "electrictian",
    "supervisor",
    "laboratorytechnician",
    "director",
    "productionmanager",
    "humanresources",
    "accountant",
    "undefined"
];
export const mineralNames = [
  "name undefined",
  "halkopirit",
  "bornit",
  "halkozin",
  "pirit",
  "markazit",
  "sfalerit",
  "galenit",
  "cinabarit",
  "wulfenit",
  "barit",
  "srebronosni galenit",
  "samorodno zivo srebro",
  "antimonit",
  "siderit",
  "hematit",
  "magnetit",
  "limonit",
  "psilomelan",
  "piroluzit",
  "uranova smola",
  "coffinit",
  "boksit",
  "samorodno zlato",
  "tennantit",
  "malahit",
  "kuprit",
  "azurit",
  "realgar",
  "torijevi minerali",
  "clay",
  "gravel",
  "limestone",
  "granite",
  "marble",
  "basalt",
  "diorite",
  "quartz",
  "slate",
  "pegmatite",
  "gypsum",
  "halite",
  "sulfur",
  "fluorite",
  "kaolin",
  "feldspar",
  "mica",
  "calcite",
  "dolomite",
  "serpentine",
  "chlorite",
  "kyanite",
  "corundum",
  "emerald",
  "ruby",
  "sapphire",
  "opal",
  "turquoise",
  "graphite",
  "plagioclase",
  "andalusite",
  "scapolite",
  "tourmaline",
  "olivine"
];
