name: Frontend CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  uploadDocker:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Push to DockerHub login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_NAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Build and push Docker
          id: push_backend
          uses: docker/build-push-action@v4
          with:
            context: .
            file: Docker
            push: true
            tags: ${{ secrets.DOCKER_HUB_NAME }}/rudniki_app:frontend

